### ISSUE TITLE
Customize document box

### ISSUE THREAD

**Issue by VadimsTalapins** [laravel-enso/documents#13]
Feature reques

### Prerequisites
* [+] Are you running the latest version?
* [+] Are you reporting to the correct repository?
* [+] Did you check the documentation?
* [+] Did you perform a cursory search?

### Description
I have a problem. How can I add custom action button to document box or "event on click" to title, image or column (file box). I want to make a checkbox "selected file" then i need to get selected file "id" and that'll.

**Comment by aocneanu** [comment]
I guess it could be a good addition so maybe we can include this in the framework, so feel free to make a PR.
