### ISSUE TITLE
Upgrade Steps existing Documents

### ISSUE THREAD

**Issue by stotes** [laravel-enso/documents#28]
I'm having a little trouble getting Documents to work after upgrading from an older version and am having difficulty understanding the upgrade steps.

Running the `artisan upgrade:enso` results in the following error when running processing the `Avatars` model.
```php
File path is starting

   Error 

  Class name must be a valid object or a string

  at vendor/laravel-enso/files/src/Upgrades/FilePath.php:75
     71▕     private function folder(string $type): string
     72▕     {
     73▕         $model = Relation::getMorphedModel($type);
     74▕ 
  ➜  75▕         return (new $model())->folder();
     76▕     }
     77▕ }
     78▕ 

      +26 vendor frames 
  27  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

In my `PrestoAdmission.php` model, I've added the `CascadesMorphMap` trait as mentioned in the [change log](https://github.com/laravel-enso/enso/blob/master/CHANGELOG.md) and additionally the `morphMap` in the `AppServiceProvider` of my application. However I'm still unable to pull back existing document relations from the model. 

Do I need to update the `documentable_type` column's data to reflect the morphMap short keys? I'm a little confused and the documentation is hard for me to understand the correct procedure for upgrading. 

Any help would be most appreciated.

**Comment by aocneanu** [comment]
if you \Log::info($type) and also Relation::getMorphedModel($type) what do you get?

**Comment by stotes** [comment]
```php
        $prestoAdmission = new PrestoAdmission();
        $alias = $prestoAdmission->getMorphClass();
        Log::info(Relation::getMorphedModel($alias));
        Log::info($alias);
```
![image](https://user-images.githubusercontent.com/941055/113227613-6def7b80-92d6-11eb-98db-1fd5a2394829.png)

**Comment by stotes** [comment]
`vendor/laravel-enso/files/src/Upgrades/FilePath.php:78`
```php 
    private function folder(string $type): string
    {
        $model = Relation::getMorphedModel($type);
        Log::info($type);
        Log::info($model);

        return (new $model())->folder();
    }
```
![image](https://user-images.githubusercontent.com/941055/113229079-8f059b80-92d9-11eb-917f-e66eeb5a1776.png)

**Comment by stotes** [comment]
I just realised that the `documentable_type` and `attachable_type` in the `documents` and `files` tables needed to be updated to reflect the removal of `App` from the namespaces. 

I updated those columns, however I am still seeing the same issue.
![image](https://user-images.githubusercontent.com/941055/113236624-908a9000-92e8-11eb-8bb8-c9fe27453246.png)

**Comment by stotes** [comment]
Looks like I figured it out. 

I misunderstood that you need to replace the `namespace` with the `getMorphedModel` type in the database columns `attachable_type` and `documentable_type`.

Thanks for the help.
